version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project

commands:
  destroy_environments:
    docker:
     - image: amazon/aws-cli

    steps:
      - run:
          name: destroy environment
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}

jobs:
  create_infrastructure:
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run: 
            name: Create Cloudformation Stack
            command:  |
              aws cloudformation deploy \
                --template-file aws-template.yaml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["80:19:36:44:04:b9:ab:95:b5:66:81:65:3e:8d:91:3c"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main.yaml

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
       - run: return 1
       - destroy_environments
      # - run:
      #     name: smoke test
      #     command: |
      #       URL="https://blog.udacity.com/" 
      #         # Test if website exists
      #       if curl -s --head ${URL} 
      #       then
      #         return 0
      #       else
      #         return 1
      #       fi
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - smoke_test

